### ISSUE TITLE
Update to new waterfall file format

### ISSUE THREAD

**Issue by wose** [wose/satnogs-monitor#22]
As pointed out by @arope99 the waterfall format changed:

> I'm using satnogs-client 1.1.2 and gr-satnogs 2.0.1-1  on armhf erpi4. The frequencies information are not on the first bytes of the waterfall files.
> 
> You can see the format as shown in the following codes taken from 
> https://gitlab.com/librespacefoundation/satnogs/gr-satnogs/-/blob/v2.0.1/lib/waterfall_sink_impl.cc
> 
> /*
>    * Write the header. Make a dummy serialization to avoid padding and
>    * alignment issues
>    */
>   d_fos.write(h.start_time, 32);
>   d_fos.write((char *)&h.fft_size, sizeof(uint32_t));
>   d_fos.write((char *)&h.samp_rate, sizeof(uint32_t));
>   d_fos.write((char *)&h.nfft_per_row, sizeof(uint32_t));
>   d_fos.write((char *)&h.center_freq, sizeof(float));
>   d_fos.write((char *)&h.endianness, sizeof(uint32_t));
> 
> The are 32  bytes of time stamp now before the freq info.

_Originally posted by @arope99 in https://github.com/wose/satnogs-monitor/issues/21#issuecomment-600902017_

**Comment by arope99** [comment]
Thanks @wose . Waterfall and spectrum works fine now.

**Comment by wose** [comment]
@arope99 Cheers! I got some code cleanup and a few almost ready features regarding decoded data left to do until the next release. This will probably happen during the next weekend.
