### ISSUE TITLE
occasional error: failed to map jobs to observations

### ISSUE THREAD

**Issue by satcolintel5** [wose/satnogs-monitor#33]
Scheduled jobs occasionally result in  the error shown  by the satnogs-monitor log option (L) with no tracking or scheduling information displayed. The waterwall of the data will scroll properly during an observation in this error state. The error usually clears within an hour or so on its own.  

Error: Failed to map jobs to observations; Failed to deserialize data to struct (in GET or POST): data did not match any variant of untagged enum JobList

![Screenshot_20220126_102942](https://user-images.githubusercontent.com/86413861/151193399-52f7dbb8-22b3-4d8b-ab9f-4829e2f67ec0.png)

observation [results](https://network.satnogs.org/observations/5366230/) for reference

Debian buster latest update
satnogs-monitor latest pull
scheduling done via satnogs-auto-scheduler and SatNOGS Observations page

**Comment by wose** [comment]
Thank you for the report. I'll take a look. There may have been some API changes we'll need to incorporate.

**Comment by satcolintel5** [comment]
Ah ha! This has been happening again on all three of my ground stations for the last 24 hours (again) and it looks like any satellite in the SatNOGS DB with a description of '-' the 'Mode' field appears the be causing this issue.

![image](https://user-images.githubusercontent.com/86413861/157299273-9569002b-2ff0-4b92-8bc4-bd722e7bc530.png)

When I removed the future observation for Blue Diamond (NORAD 42786) from all three stations, the display error in satnogs-monitor corrected. Red Diamond (NORAD 42783 ) also caused this display error (verified by scheduling a few observations) due to 'Mode' defined as '-' (null). Green Diamond (42785) has Mode defined as 'FM' and does not cause this display problem. 

I will make a request in SatNOGS DB to have this updated.

**Comment by wose** [comment]
Thank you for the additional Info.

`Mode` is defined as `string` on our side, but it seems to be an `Option<string>` instead. That's an easy fix.
