### ISSUE TITLE
cargo-release: revspec '389fafb' for tui-rs not found

### ISSUE THREAD

**Issue by kerel-fs** [wose/satnogs-monitor#4]
Following the installation instructions in the README I get the following error:
```
$ cargo run --release
    Updating crates.io index
    Updating git repository `https://github.com/wose/rust-gpredict.git`
    Updating git repository `https://github.com/myfreeweb/systemstat.git`
    Updating git repository `https://github.com/wose/tui-rs.git`
error: failed to load source for a dependency on `tui`

Caused by:
  Unable to update https://github.com/wose/tui-rs.git#389fafb1

Caused by:
  revspec '389fafb1acc101c35b31a820b7d5ad882fce144f' not found; class=Reference (4); code=NotFound (-3)
```

My guess is that this was caused by a force-push to [wose/tui-rs](https://github.com/wose/tui-rs), such that the old commit (which is referenced in `Cargo.lock`) got orphaned.
- [old commit,  orphaned](https://github.com/wose/tui-rs/commit/389fafb1acc101c35b31a820b7d5ad882fce144f)
- [new commit, in master branch](https://github.com/wose/tui-rs/commit/4cd29f639704afb8174b0366e6a7b384fadd4020)

Running `cargo update -p tui` fixed this problem (unfortunately I run into an other problem with building tui now, will follow-up via satnogs-forum).

**Comment by wose** [comment]
Thx @kerel-fs ,

good catch! You're right. This was me doing some things in the wrong order. I'll setup some CI to catch those errors sooner.
