### ISSUE TITLE
check changes in satnogs api pagination

### ISSUE THREAD

**Issue by wose** [wose/satnogs-monitor#48]
See https://community.libre.space/t/satnogs-monitor-not-running-solved/11590

**Comment by michaelachrisco** [comment]
Im getting the same issue as within the form: 

![image](https://github.com/wose/satnogs-monitor/assets/398491/bd1ada54-2ae8-4144-a69d-0ec50656022b)


Even when the ground station has future observations, the tool will not update.

**Comment by alitbutt** [comment]
As fredy mentioned here : [https://community.libre.space/t/satnogs-monitor-not-running-solved/11590](https://community.libre.space/t/satnogs-monitor-not-running-solved/11590 ) 
; a recent change in pagination technique to use cursors needs a slight change in [/satnogs-network-client/src/client.rs](https://github.com/wose/satnogs-monitor/tree/master/satnogs-network-client/src/client.rs)

Specifically line 37 : 53 needs to be replaced with this version:

        let mut pages_remaining = true;
        let mut filter_cursor = "".to_owned();
        while pages_remaining {
            pages_remaining = false;
            let mut filter = filter.clone();
            filter.push(("cursor", &filter_cursor));
            match self.client.get_with((), &filter) {
                Ok(resp) => {
                    let resp_data: Response<ObservationList> = resp; 
                    let resp_headers = resp_data.headers();
                    if resp_headers.contains_key("link") {
                        let link_header = &resp_headers["Link"];
                        let res = parse_link_header::parse(link_header.to_str().unwrap());
                        assert!(res.is_ok());

                        let val = res.unwrap();
                        let next_link = val.get(&Some("next".to_string()));
                        if next_link.is_some() {
                            let next_url = &next_link.unwrap();
                            filter_cursor = next_url.queries["cursor"].to_string();
                            pages_remaining = true;
                        }
                    }

                    let ObservationList::Array(obs) = resp_data.into_inner();
                    observations.extend_from_slice(&obs);
                }
                Err(Error::HttpError(404, _)) => break,
                Err(e) => return Err(e),
            }
        }

... will create a PR shortly.
This code has an added dependency for[ parse_link_header](https://docs.rs/parse_link_header/) in satnogs-network-client

I see API requests at some point getting throttled; might have to handle that case separately.

**Comment by kng** [comment]
what is the progress on this ? rumors tells me that it is working.

**Comment by toine512** [comment]
A PR exists https://github.com/wose/satnogs-monitor/pull/50

**Comment by kng** [comment]
Building now and testing on station [1888](https://network.satnogs.org/stations/1888/), which is usually pretty busy.
I think there's some issue still, it seems like it is not fetching the entire batch of [future observations](https://network.satnogs.org/observations/?station=1888) properly.
It is selecting one that is on page 2, but the next one that should run is on page 3.

Please try with `config.toml` with:
```
[[stations]]
satnogs_id = 1888
```

**Comment by wose** [comment]
indeed, thx for checking

**Comment by wose** [comment]
Fixed in [86f5889](https://github.com/wose/satnogs-monitor/commit/86f5889b3be27c4fe42acabc3decd7e8137b4034)
